[package]
name                   = "youpipe-sys"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
description            = "Miri/loom-transparent synchronization primitives and cache padding for youpipe"
repository.workspace   = true
license.workspace      = true
keywords               = ["cache-padding", "concurrency", "loom", "miri"]
categories             = ["concurrency"]

[dependencies]
parking_lot = "0.12"

[target."cfg(loom)".dependencies]
loom = "0.7"

[lints]
workspace = true
